### ISSUE TITLE
Error when trying to connect UCS Central using port 80. It throws Url Error.

### ISSUE THREAD

**Issue by tanmayx** [CiscoUcs/ucscentralsdk#14]
* ucscentralsdk version: 0.9.0.0 (Latest code from GitHub)
* Python version: 2.7.12
* Operating System: Windows 10

Trying to connect to UCS Central using port 80. Without the try block, it throws URL Error. 
Within the try block, the code just hangs since it waits for the exception which never comes.
I would suggest that customized exception should be thrown to a user.

With try block, code just hangs -
_handle = UcsCentralHandle(ip, username, password, port=80)
try:
    handle.login()
except Exception as e:
    print e_

Without try block, the below error is thrown - 
 _"URLError: <urlopen error [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)>_

**Comment by parag-may4** [comment]
Ucs Central only supports https remote access and that too only via port 443. 
So made changes to raise an exception if any other port other than 443 is being tried.

https://github.com/CiscoUcs/ucscentralsdk/pull/17
