### ISSUE TITLE
Local download throwing 404 error with ucs central version 1.5

### ISSUE THREAD

**Issue by tanmayx** [CiscoUcs/ucscentralsdk#20]
ucscentralsdk version: _Latest from github_
Python version: _2.7.12_
Operating System: _Windows 10_

Description:
_Local download throwing 404 error for backup, export config and tech support API's._

Observation:
_Server: Apache/2.4.12 (Unix) CiscoSSL/1.0.1t.4.13.282_
_Content-Length: 267_
_Connection: close_
_Content-Type: text/html; charset=iso-8859-1_

_2016-10-04 17:05:31,540 - ucscentral - DEBUG - HTTP Error 404: Not Found_

**Comment by parag-may4** [comment]
-> Back-end has stopped supporting local download from 1.5 release onwards, so restricting the same with SDK as well and not throwing exception if local download is tried with 1.5.
-> Fixed the issue with PR: https://github.com/CiscoUcs/ucscentralsdk/pull/26
