### ISSUE TITLE
get_ucscentral_cco_image() throws TypeError

### ISSUE THREAD

**Issue by tanmayx** [CiscoUcs/ucscentralsdk#24]
ucscentralsdk version: Latest from github
Python version: 2.7.12
Operating System: Windows 10

**Description**
Trying to execute get_ucscentral_cco_image() API. It throws TypeError.

**What I Did**
get_cco_firmware_image(image_name="ucs-central.1.5.1b.iso", 
                                        username=username,
                                        password=password,
                                        download_dir=local_dir_path)

**It throws following error -**
c:\python27\lib\site-packages\ucscentralsdk-0.9.0.0-py2.7.egg\ucscentralsdk\utils\ucscentralfirmware.pyc in get_cco_firmware_image(image_name, username, password, download_dir, mdf_id_list, proxy, progress)
    188         file_dir=download_dir,
    189         proxy=proxy,
--> 190         progress=progress)
    191
    192

TypeError: get_ucscentral_cco_image() got an unexpected keyword argument 'progress'

**Comment by parag-may4** [comment]
Fixed the issue with PR: https://github.com/CiscoUcs/ucscentralsdk/pull/25
